lsi: false
safe: true
source: semplea.github.io
incremental: false
title: Just another blog
description: Hopefully something interesting
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-minimal
